### ISSUE TITLE
What should be removed?

### ISSUE THREAD

**Issue by jacobpennington** [jacobpennington/nems-lite#2]
1) database
2) GUI
3) xforms
4) preprocessors and initializers (except for very general ones - nothing lab specific)
5) plugins
6) data folders (results, recordings, etc)
7) outdated scripts
8) plots (except a few very general ones). 90% of the plot code is either standardized formatting or specific to our lab's models and data.
9) anything with cellid or batch arguments (remove or refactor)
10) hard-coded references to est/val/pred/etc
11) unused or commented-out code -- try [vulture](https://github.com/jendrikseipp/vulture)

**Comment by svdavid** [comment]
We should leave support for cellid and batch labeling. Maybe better terms?  But it's useful to give NEMS some kind of meta data so that it can save to files with names that are meaningful to the user. Plus we want to make the system compatible with existing NEMS.

**Comment by jacobpennington** [comment]
Yes including meta information makes sense, I was referring to functions like `fit_model_xform` that require a cellid & batch.
