### ISSUE TITLE
Rename some core NEMS functions to match scipy conventions

### ISSUE THREAD

**Issue by jacobpennington** [jacobpennington/nems-lite#6]
When possible, we should name NEMS features in a way that is "obvious" to some one familiar with the SciPy stack, since so much of NEMS (and most other scientific packages) is built directly off of that. Will have to think about what all to add to this list, but for now:

1) `Signal.as_continuous( )` should be renamed to `Signal.asarray( )` or `Signal.values`. I like the latter personally, but I think either is better than the current version.

2) I hate this as I write it but... call modules layers instead? Would be more similar to NN lingo and avoid some ambiguity in documentation (i.e whether "module" refers to a NEMS module or a python module). Not a big deal since this is usually clear from context, but worth considering.

3) Rename `Module.phi` to `Module.parameters` or `Module.variables` or similar, more descriptive. Finding that `parameters` isn't ideal either though, b/c it makes the docstrings for the Modules potentially confusing. Like:
```
"""
Parameters
------------
parameters : dict
    ...

"""
```
If we go with the Phi / Variable classes I mocked up, then I think `Module.variables` would make the most sense (since fetching that attribute would return a dict-like structure filled with Variable objects).

4) Remove unnecessary references to  NEMS in class/function names. I.e. `NemsModelSpec` or `NemsModule` should just be ModelSpec or Module. If clarity is needed in documentation, refer to the import path (like `nems.Modelspec` or `nems.modules.Module` ) if feasible instead of `NEMS Module`.

5) Rename ModelSpec to Model.

**Comment by svdavid** [comment]
All sound good. One possibility for simplifying the transition would be to preserve backward compatibility where possible. Eg, as_continuous() can remain an alias for values.
