### ISSUE TITLE
Remove TF dependency?

### ISSUE THREAD

**Issue by jacobpennington** [jacobpennington/nems-lite#7]
If I understand Stephen's comments correctly, want to isolate TF imports so that it can be removed from dependency list (i.e. you only need it if you're using it). 

Alternative/in addition: put all high-level TF stuff in an entirely separate nems-tf package with its own set of install instructions.

**Comment by svdavid** [comment]
I would argue that we should not have a separate package but should make it an optional component of the pip install. Python makes it easy to restrict tf imports to places that specifically require it, so the package should operate everywhere else without requiring a TF install.
Can we also remove requests and sqlalchemy dependencies?

**Comment by jacobpennington** [comment]
Yes those can be removed, also the pyqt stuff for the gui.
